# Generated by Django 5.0.1 on 2025-10-21 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'MUSCULO',
            },
        ),
        migrations.CreateModel(
            name='NivelDificultad',
            fields=[
                ('dificultad_id', models.AutoField(db_column='DIFICULTAD_ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=30)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
            ],
            options={
                'db_table': 'NIVEL_DIFICULTAD',
            },
        ),
        migrations.CreateModel(
            name='TipoEjercicio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'TIPO_EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
                ('video_url', models.FileField(blank=True, db_column='VIDEO_URL', null=True, upload_to='ejercicios/gifs/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
                ('musculo', models.ForeignKey(db_column='MUSCULO_ID', on_delete=django.db.models.deletion.CASCADE, to='api_ejercicio.musculo')),
                ('tipo_ejercicio', models.ForeignKey(db_column='TIPO_EJERCICIO_ID', on_delete=django.db.models.deletion.CASCADE, to='api_ejercicio.tipoejercicio')),
            ],
            options={
                'db_table': 'EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='ProgresoEjercicio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, db_column='FECHA')),
                ('repeticiones_realizadas', models.PositiveIntegerField(db_column='REPETICIONES_REALIZADAS', null=True)),
                ('peso_usado', models.FloatField(db_column='PESO_USADO', null=True)),
                ('duracion_minutos', models.FloatField(db_column='DURACION_MINUTOS', null=True)),
                ('ejercicio', models.ForeignKey(db_column='EJERCICIO_ID', on_delete=django.db.models.deletion.CASCADE, to='api_ejercicio.ejercicio')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PROGRESO_EJERCICIO',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('descripcion', models.TextField(db_column='DESCRIPCION', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
                ('nivel_dificultad', models.ForeignKey(db_column='NIVEL_DIFICULTAD_DIFICULTAD_ID', on_delete=django.db.models.deletion.PROTECT, to='api_ejercicio.niveldificultad')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RUTINA',
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('repeticiones', models.PositiveIntegerField(db_column='REPETICIONES', null=True)),
                ('orden', models.PositiveIntegerField(db_column='ORDEN', null=True)),
                ('ejercicio', models.ForeignKey(db_column='EJERCICIO_ID', on_delete=django.db.models.deletion.CASCADE, to='api_ejercicio.ejercicio')),
                ('rutina', models.ForeignKey(db_column='RUTINA_ID', on_delete=django.db.models.deletion.CASCADE, to='api_ejercicio.rutina')),
            ],
            options={
                'db_table': 'RUTINA_EJERCICIO',
            },
        ),
    ]
