# Generated by Django 5.0.1 on 2025-10-29 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ejercicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='nivel_dificultad',
            field=models.ForeignKey(blank=True, db_column='NIVEL_DIFICULTAD_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_ejercicio.niveldificultad'),
        ),
    ]
