# Generated by Django 5.0.1 on 2025-10-29 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ejercicio', '0002_ejercicio_nivel_dificultad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioRutina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FECHA')),
                ('hora', models.TimeField(blank=True, db_column='HORA', null=True)),
                ('completada', models.BooleanField(db_column='COMPLETADA', default=False)),
                ('notas', models.TextField(blank=True, db_column='NOTAS', null=True)),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(db_column='RUTINA_ID', on_delete=django.db.models.deletion.CASCADE, to='api_ejercicio.rutina')),
            ],
            options={
                'db_table': 'CALENDARIO_RUTINA',
                'unique_together': {('perfil', 'rutina', 'fecha')},
            },
        ),
    ]
