# Generated by Django 5.0.1 on 2025-11-09 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ejercicio', '0003_calendariorutina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_guardadas', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardadas', to='api_ejercicio.rutina')),
            ],
            options={
                'unique_together': {('rutina', 'perfil')},
            },
        ),
    ]
