# Generated by Django 5.0.1 on 2025-10-21 02:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('correo', models.EmailField(db_column='CORREO', max_length=254)),
                ('asunto', models.CharField(db_column='ASUNTO', max_length=150)),
                ('mensaje', models.TextField(db_column='MENSAJE')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='FECHA_ENVIO')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
            ],
            options={
                'db_table': 'CONTACTO',
            },
        ),
        migrations.CreateModel(
            name='GrupoEntrenamiento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
            ],
            options={
                'db_table': 'GRUPO_ENTRENAMIENTO',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=100)),
                ('contenido', models.TextField(db_column='CONTENIDO')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
            ],
            options={
                'db_table': 'TIP',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'TIPO_OBJETIVO',
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
            ],
            options={
                'db_table': 'TIPO_SANGRE',
            },
        ),
        migrations.CreateModel(
            name='SaludUsuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('frecuencia_cardiaca_reposo', models.PositiveIntegerField(db_column='FRECUENCIA_CARDIACA_REPOSO', null=True)),
                ('enfermedades_preexistentes', models.TextField(db_column='ENFERMEDADES_PREEXISTENTES', null=True)),
                ('lesiones_actuales', models.TextField(db_column='LESIONES_ACTUALES', null=True)),
                ('alergias', models.TextField(db_column='ALERGIAS', null=True)),
                ('fuma', models.BooleanField(db_column='FUMA', default=False)),
                ('bebe', models.BooleanField(db_column='BEBE', default=False)),
                ('fecha_actualizacion', models.DateField(auto_now=True, db_column='FECHA_ACTUALIZACION')),
                ('tipo_sangre', models.ForeignKey(db_column='TIPO_SANGRE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.tiposangre')),
            ],
            options={
                'db_table': 'SALUD_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=30, null=True)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(db_column='FECHA_NACIMIENTO', null=True)),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
                ('foto', models.ImageField(blank=True, db_column='FOTO', null=True, upload_to='perfiles/fotos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('salud_usuario', models.ForeignKey(blank=True, db_column='SALUD_USUARIO_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.saludusuario')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'PERFIL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuenoUsuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FECHA')),
                ('horas_dormidas', models.FloatField(db_column='HORAS_DORMIDAS', null=True)),
                ('calidad_sueno', models.CharField(db_column='CALIDAD_SUEÑO', max_length=20, null=True)),
                ('despertares_nocturnos', models.PositiveIntegerField(db_column='DESPERTARES_NOCTURNOS', null=True)),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SUEÑO_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('contenido', models.TextField(db_column='CONTENIDO')),
                ('media_url', models.FileField(blank=True, db_column='MEDIA_URL', null=True, upload_to='publicaciones/media/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_column='ULTIMA_ACTUALIZACION')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PUBLICACION',
            },
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('peso_kg', models.FloatField(db_column='PESO_KG', null=True)),
                ('altura_cm', models.FloatField(db_column='ALTURA_CM', null=True)),
                ('comentario', models.TextField(db_column='COMENTARIO', null=True)),
                ('imc_calculado', models.FloatField(db_column='IMC_CALCULADO', null=True)),
                ('fecha', models.DateField(auto_now_add=True, db_column='FECHA')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PROGRESO_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('contenido', models.TextField(db_column='CONTENIDO')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OPINION',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoUsuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('meta_peso_kg', models.FloatField(db_column='META_PESO_KG', null=True)),
                ('meta_grasa_corporal', models.FloatField(db_column='META_GRASA_CORPORAL', null=True)),
                ('fecha_inicio', models.DateField(db_column='FECHA_INICIO')),
                ('fecha_meta', models.DateField(db_column='FECHA_META', null=True)),
                ('estado', models.CharField(db_column='ESTADO', max_length=50)),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('tipo_objetivo', models.ForeignKey(db_column='TIPO_OBJETIVO_ID', on_delete=django.db.models.deletion.CASCADE, to='App.tipoobjetivo')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OBJETIVO_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='NutricionRegistro',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FECHA')),
                ('comida', models.CharField(db_column='COMIDA', max_length=100)),
                ('calorias', models.FloatField(db_column='CALORIAS', null=True)),
                ('proteinas', models.FloatField(db_column='PROTEINAS', null=True)),
                ('carbohidratos', models.FloatField(db_column='CARBOHIDRATOS', null=True)),
                ('grasas', models.FloatField(db_column='GRASAS', null=True)),
                ('descripcion', models.TextField(db_column='DESCRIPCION', null=True)),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NUTRICION_REGISTRO',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='TIPO', max_length=50)),
                ('mensaje', models.CharField(db_column='MENSAJE', max_length=255)),
                ('leida', models.BooleanField(db_column='LEIDA', default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='FECHA')),
                ('perfil_destino', models.ForeignKey(db_column='PERFIL_DESTINO_ID', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('perfil_origen', models.ForeignKey(blank=True, db_column='PERFIL_ORIGEN_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NOTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='MensajePrivado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('contenido', models.TextField(db_column='CONTENIDO')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='FECHA_ENVIO')),
                ('leido', models.BooleanField(db_column='LEIDO', default=False)),
                ('emisor', models.ForeignKey(db_column='EMISOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(db_column='RECEPTOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MENSAJE_PRIVADO',
            },
        ),
        migrations.CreateModel(
            name='HistorialMedidas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('grasa_corporal', models.FloatField(db_column='GRASA_CORPORAL', null=True)),
                ('masa_muscular', models.FloatField(db_column='MASA_MUSCULAR', null=True)),
                ('cintura_cm', models.FloatField(db_column='CINTURA_CM', null=True)),
                ('cadera_cm', models.FloatField(db_column='CADERA_CM', null=True)),
                ('progreso_usuario', models.ForeignKey(db_column='PROGRESO_USUARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='App.progresousuario')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HISTORIAL_MEDIDAS',
            },
        ),
        migrations.CreateModel(
            name='GrupoMiembro',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='ROL', max_length=30)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, db_column='FECHA_INGRESO')),
                ('activo', models.BooleanField(db_column='ACTIVO', default=True)),
                ('grupo_entrenamiento', models.ForeignKey(db_column='GRUPO_ENTRENAMIENTO_ID', on_delete=django.db.models.deletion.CASCADE, to='App.grupoentrenamiento')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GRUPO_MIEMBRO',
            },
        ),
        migrations.AddField(
            model_name='grupoentrenamiento',
            name='perfil_creador',
            field=models.ForeignKey(db_column='PERFIL_CREADOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('comentario', models.TextField(db_column='COMENTARIO')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('publicacion', models.ForeignKey(db_column='PUBLICACION_ID', on_delete=django.db.models.deletion.CASCADE, to='App.publicacion')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'COMENTARIO',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoUsuario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateField(auto_now_add=True, db_column='FECHA_SEGUIMIENTO')),
                ('vigente', models.BooleanField(db_column='VIGENTE', default=True)),
                ('seguido', models.ForeignKey(db_column='SEGUIDO_ID', on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
                ('seguidor', models.ForeignKey(db_column='SEGUIDOR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SEGUIMIENTO_USUARIO',
                'unique_together': {('seguidor', 'seguido')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='FECHA')),
                ('publicacion', models.ForeignKey(db_column='PUBLICACION_ID', on_delete=django.db.models.deletion.CASCADE, to='App.publicacion')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LIKE',
                'unique_together': {('perfil', 'publicacion')},
            },
        ),
        migrations.CreateModel(
            name='FavoritoPublicacion',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha_agregado', models.DateField(auto_now_add=True, db_column='FECHA_AGREGADO')),
                ('publicacion', models.ForeignKey(db_column='PUBLICACION_ID', on_delete=django.db.models.deletion.CASCADE, to='App.publicacion')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FAVORITO_PUBLICACION',
                'unique_together': {('perfil', 'publicacion')},
            },
        ),
    ]
