# Generated by Django 5.0.1 on 2025-10-26 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(db_column='GENERO', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EstiloVidaUsuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nivel_estres', models.CharField(db_column='NIVEL_ESTRES', max_length=30, null=True)),
                ('horas_sueno', models.FloatField(db_column='HORAS_SUENO', null=True)),
                ('calidad_sueno', models.CharField(db_column='CALIDAD_SUENO', max_length=20, null=True)),
                ('alimentacion', models.CharField(db_column='ALIMENTACION', max_length=50, null=True)),
                ('actividad_laboral', models.CharField(db_column='ACTIVIDAD_LABORAL', max_length=50, null=True)),
                ('entorno_entrenamiento', models.CharField(db_column='ENTORNO_ENTRENAMIENTO', max_length=50, null=True)),
                ('frecuencia_entrenamiento', models.CharField(db_column='FRECUENCIA_ENTRENAMIENTO', max_length=30, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='FECHA_ACTUALIZACION')),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ESTILO_VIDA_USUARIO',
            },
        ),
    ]
