# Generated by Django 5.0.1 on 2025-10-27 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rutina_recomendada', models.CharField(db_column='RUTINA_RECOMENDADA', max_length=120)),
                ('top3_recomendaciones', models.JSONField(db_column='TOP3_RECOMENDACIONES', null=True)),
                ('ejercicios', models.JSONField(db_column='EJERCICIOS', null=True)),
                ('parametros_entrada', models.JSONField(db_column='PARAMETROS_ENTRADA', null=True)),
                ('modelo_version', models.CharField(db_column='MODELO_VERSION', default='AthletIA v8', max_length=50)),
                ('precision_modelo', models.FloatField(db_column='PRECISION_MODELO', null=True)),
                ('fecha_recomendacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_RECOMENDACION')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], db_column='ESTADO', default='pendiente', max_length=30)),
                ('perfil', models.ForeignKey(db_column='PERFIL_ID', on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendación IA',
                'verbose_name_plural': 'Recomendaciones IA',
                'db_table': 'RECOMENDACION_IA',
                'ordering': ['-fecha_recomendacion'],
            },
        ),
    ]
